
markdown: redcarpet
pygments: true


name:        JustinAven
dev:         true

safe:        false
port:        4000
baseurl:     /
url:         http://localhost:4000
exclude:     [ sass ]

source:      .
destination: ./_site

permalink:   /:categories/:title/